### ISSUE TITLE
Prepare for recording audio + video for Balloons and Static Electricity Interview

### ISSUE THREAD

**Issue by samreid** [phetsims/a11y-research#2]
From #1 we decided to investigate recording html5 audio from the microphone and combining that with some way to record the simulation:
* scenery input events would require addition of support for recording and playing back parallel dom events
* or we could phet-io instrument the simulation and record states, then write a script that does playback based on states.

I volunteered to help on this, noting that my time is somewhat tied up for the near future.  It was suggested that @jessegreenberg help out as possible.

It looks like a good place to start investigation with the audio will be https://webaudiodemos.appspot.com/AudioRecorder/index.html

I'm marking this as high-priority to put it on my todo-list, and because @emily-phet said it would be helpful if it was available soon.

**Comment by samreid** [comment]
> I'm marking this as high-priority 

I'll hold off on this until @mattpen assigns the GitHub labels, see #3

**Comment by samreid** [comment]
On Nov 3, 2016 6:14 PM, "Sam Reid" <reids@colorado.edu> wrote:

    Doug,

    Are we permitted to store microphone audio data from student computers on Metacog?  We are setting up remote interviews for our accessibility features, and would like to investigate using Metacog for this data, if possible.

    Best Regards,
    Sam

**Comment by samreid** [comment]
Metacog said it is OK for us to store audio data on their servers as long as it is permitted by our own IRB.

**Comment by samreid** [comment]
10 seconds of silence recorded by https://webaudiodemos.appspot.com/AudioRecorder/index.html is weighing in around 1.8MB.  This is at least an order of magnitude higher than anything we have sent to metacog before, so we may run into bandwidth problems.  Perhaps cutting the bitrate or recording as mono could reduce this somewhat.

**Comment by samreid** [comment]
Doug also suggested:

> If you have enough processing power on the client, you can also convert the audio to a good format like speex (as opposed to a bulky base64). Speex and other formats can also be sent through Google's speech recognition API - which will return a text transcription along with a confidence measure. You could pack the translation/confidence into the metacog event along with the audio. Alternatively, you could just use metacog to gather audio-only soundBite events and post process after using our DataRequest API to retrieve them

**Comment by samreid** [comment]
@jessegreenberg I was about to start instrumenting Balloons and Static Electricity for phet-io, when I noticed that most of your work is being done in a branch.  If I instrument master, we will have a problematic merge.  If I instrument accessible-instance, we may wish to coordinate efforts.  How should we proceed?

**Comment by jessegreenberg** [comment]
@samreid I will work on merging the accessibility branch into master now in https://github.com/phetsims/balloons-and-static-electricity/issues/194.

**Comment by samreid** [comment]
OK Good luck!

**Comment by samreid** [comment]
@kathy-phet said: 

> We must record what is emitted by the computer, because the screen reader says things we must hear. 

I don't know if this will be technically feasible--we will have to investigate it.  @emily-phet said we may be able to request that interviewees use speakers instead of headphones, but if we can support system recording it would be best.

**Comment by jessegreenberg** [comment]
@samreid the merge has been completed, but I will be continuing to work in the repo throughout the week.  If you would like assistance with any part of the instrumentation please let me know and we can coordinate!

**Comment by samreid** [comment]
Thanks @jessegreenberg!  In #1 I also pointed out that recording audio may be a significant development effort at the moment, and recommended to investigate Zoom for now.

**Comment by samreid** [comment]
Breakdown of tasks required to build something that may work here:

1. Build something like https://webaudiodemos.appspot.com/AudioRecorder/index.html that reads data from an audio channel.
2. The data amount is an order of magnitude larger than what we have previously supported for our services.  Will we have to compress it?
3. Data will be sent in chunks to increase the probability that we retrieve it.  We will need tools after the data is retrieved that reassemble it into something listenable.
4. Balloons and Static Electricity should be instrumented for PhET-iO
5. We need to build a new playback engine that supports playing back states.
6. Testing on a variety of platforms to understand what platforms this might work on
7. Determine whether we can record system audio (which will double the bandwidth requirement)
8. Recording keys and mouse events on top of states and making it possible to visualize/understand them.

None of the above will work without a server that can deal with the data.  I wonder if that step can be circumvented by giving the interviewee a file that must be downloaded then emailed?  But that would certainly be a hassle for the interviewee, and email probably wouldn't support 200MB+ attachments.  If we end up building our own server program for this, it will take some time.

**Comment by aadish** [comment]
@samreid might want look at this library http://resumablejs.com/
Its a good way to upload large data to the server but as you said server needs to handle it

**Comment by samreid** [comment]
Thanks @aadish, if we cannot support streaming the data in real-time, we can look into resumablejs as a fallback.

**Comment by emily-phet** [comment]
@samreid - what if we only focus on capturing video, no audio?

**Comment by samreid** [comment]
> @samreid - what if we only focus on capturing video, no audio?

That would be significantly easier. In that case, we could get by with steps (4) and (5) above, with the option to investigate step (8).

**Comment by emily-phet** [comment]
@samreid - video alone would be very helpful, it would be great if we could proceed with this option (4 and 5 above).

**Comment by ariel-phet** [comment]
@emily-phet I think it is fine for @jessegreenberg to work on this (except for his 25% or so time on sims, I think we long agreed you direct his a11y time). @samreid I don't think has much bandwidth to work on this unfortunately. That would be a discussion to have with @kathy-phet as there seems to be lots of iO stuff to still push on.

**Comment by samreid** [comment]
We would like to investigate supporting visual record and playback for Balloons and Static Electricity via PhET-iO instrumentation.  I originally thought this would be suitable to work on with @jbphet as a first simulation to instrument, but after review in https://github.com/phetsims/balloons-and-static-electricity/issues/201 I discovered there is a lot of new code related to accessibility that would complicate the task, and that @jbphet and I should actually start with Gravity Force Lab, as originally planned.

**Comment by samreid** [comment]
On hold while https://github.com/phetsims/balloons-and-static-electricity/issues/204 is in progress.

**Comment by samreid** [comment]
After https://github.com/phetsims/balloons-and-static-electricity/issues/204 is done, we need a way to play back a simulation from states.  I'll close this issue and open a new issue about adding that feature to PhET-iO playbacks.

**Comment by jbphet** [comment]
@samreid and I discussed this, and we are realizing that instrumenting the sim using PhET-iO and then using the state playback capability may have several shortcomings for what we believe @emily-phet would like to accomplish here.  Here are some of the potential issues:

+ playback of recorded state data will not depict the focus rectangles
+ playback of recorded state data will not trigger auditory descriptions
+ playback of recorded state data will not show state changes of UI components, for instance, the pressing of buttons
+ playback of recorded state data will not show interaction with the PhET menu and the keyboard dialog
+ playback of recorded state data will not show the position of pointers
+ performance of the simulation may be reduced when collecting state data- we've seen some indications of this while testing Balloons and Static Electricity in the PhET-iO state wrapper and will log a separate issue for it

What we **do** think we will be able to show is the location and movement of the balloons and charges, the states of the radio buttons, and whether the wall is on or off.

It seems to @samreid and me that these deficiencies mean that using the PhET-iO state playback approach for collecting data for remote interviews may not be ideal, at least not in the short term.  We should probably go back to looking at using some other remote screen sharing solution, such as Zoom, for recording these interviews.  If Zoom is interfering in some way with the operation of accessibility features, we should report it to them since they have expressed a desire to be fully accessible (see https://github.com/phetsims/a11y-research/issues/1#issuecomment-258991512).  Having a means of doing accessibility interviews that doesn't require a sim to be fully instrumented with PhET-iO is probably a good idea anyway, since it removes some of the coupling between PhET-iO and the development of accessibility features.

That being said, we are currently planning on continuing with instrumenting Balloons and Static Electricity with PhET-iO, and if the features listed above serve the desired purpose, it should be available reasonably soon.

**Comment by jbphet** [comment]
Assigning to @emily-phet and @ariel-phet to get their input on how the information in the comment above affects the plan for obtaining the needed audio and video recordings.

**Comment by kathy-phet** [comment]
Question -- Can the input event recorder be leveraged to accept all input events (like the tab navigation) to enable some of these missing features?

**Comment by samreid** [comment]
The input event recorder could record the position of pointers rather easily, I'll leave it up to @jonathanolson and @jessegreenberg to discuss whether scenery could record tab navigation/focus events/etc.

**Comment by jonathanolson** [comment]
Those aren't Scenery events, but listeners could be added (see https://www.w3.org/TR/page-visibility/).

**Comment by samreid** [comment]
@jonathanolson if I understand it correctly, the input events are intercepted by the assistive technology and routed to the browser through another API, and hence cannot be observed using the listeners you mentioned.  I have not tested this.  @jessegreenberg can you comment?

**Comment by jonathanolson** [comment]
Sorry, I mis-interpreted tab-navigation as determining if our sim was in an active browser tab or not.

@samreid that sounds right. May be possible (desirable?) to add the ability to record accessibility events, so that those could be played back (@jessegreenberg has more knowledge).

**Comment by jessegreenberg** [comment]
Yes, we should investigate at what level we can record events, I am a unsure about how far we can go here too.

While a screen reader is on, any input event (including touch and mouse events, depending on the AT) might be intercepted.  But my understanding is that after the AT manages the it, it will pass *some* event along to the browser, even if it is different than the event that was originally entered.  We should be able to record these.

**Comment by samreid** [comment]
For example, RadioButton.js has this code:

```js
        // listen for keyboard events and fire model
        domElement.addEventListener( 'click', function() {
          fire();
        } );
```

For RadioButtons, this is the event we would need to record and play back, right?  And for other types such as Buttons, etc, there would be something different but equally simple?

If so, then it seems we should route these through something like scenery Input.js, which would look like this:

```js
        // listen for keyboard events and fire model
        domElement.addEventListener( 'click', function() {
          Input.dispatchDOMEvent( self, fire )
        } );
```

However, I do not know if this is enough information for scenery to be able to play back this kind of events.  And how would scenery access the "fire" method during playbacks?  Would it need to be a prototype method?

**Comment by jonathanolson** [comment]
I was imagining something like Scenery internally having something vaguely resembling:
```js
addPeerListeners( domElement ) {
  // ...
  domElement.addEventListener( 'click', Input.accessibilityClick );
  // ...
}
```
where somewhere upon creation of the domElement it gets those listeners added. Then in the client:
```js
node.addInputListener( {
  accessibilityClick: function( someSceneryEventTypeWithAllInfoNeeded ) {
    fire();
  }
} );
```
or
```js
peer.addListener( 'click', fire );
```
with whatever is convenient.

**Comment by emily-phet** [comment]
@jbphet and @samreid Thanks for the thorough investigation here! A couple of thoughts:
-  Because of the immediate challenges listed above, we'll pursue other interview data collection avenues (e.g., @jessegreenberg is investigating accessibility issues with Zoom to see if we can use Zoom's screensharing capability for this). While screensharing is definitely better than nothing, there are still some issues (e.g., potentially usability issues for the user; audio issues when simultaneously recording screen reader, user, and interviewer; security considerings for the user, etc.) so the future capability of PhET-iO to support this type of data collection (for PhET and others) would be beneficial. 
- As a funding source, I believe in the long term PhET-iO will need to be able to record accessibility-related input/output events just as easily as the typical mouse or touch input and visual output currently supported. If not already being done, perhaps it would be useful to document the findings from this issue in a PhET-iO issue, and track needs and progress towards ultimately being able to record a broader range of input and output events.

**Comment by jessegreenberg** [comment]
This is no longer high priority.

In https://github.com/phetsims/a11y-research/issues/16, we tested Zoom with a number of screen readers and found that as long as the user has access to the zoom hotkeys they are able to use it. We did a test recording with a screen reader user and were able to hear the AT output in that case.

That being said, it is still possible to run into these problems:
>e.g., potentially usability issues for the user; audio issues when simultaneously recording screen reader, user, and interviewer; security considerings for the user, etc.) so the future capability of PhET-iO to support this type of data collection (for PhET and others) would be beneficial.

**Comment by terracoda** [comment]
Yes, I have used zoom successfully three times now with screen reader users. However, there are performance issues when screen is being shared, so I decided to go without screen sharing.

Screen sharing worked ok for Ohm's Law, but not for Balloons and Static Electricity.

**Comment by terracoda** [comment]
I continue to use Zoom for remote  sessions with screen reader consultants. Zoom is quite accessible to screen reader users (both JAWS and VO), however, screen sharing takes up a lot of resources, often making it impossible to do the session with screen sharing on.

**Comment by jessegreenberg** [comment]
Thanks for the updates @terracoda. I think this issue can be closed. Based on the state of this issue and recent comments about priorities for a11y and phet-io (https://github.com/phetsims/phet-io/issues/995#issuecomment-337219811), I don't think we have plans to work on this for now. Do you feel that zoom has been working well enough for interviewing, or should we create a new issue to look into other alternatives to zoom?

**Comment by terracoda** [comment]
For working with consultants, Zoom is fine. For research interviews, I don't think zoom will cut it because it is difficult to successful screen sharing. If only audio is captured, it can work, though.

I was wondering if we should close this issue, too. I think it is safe to close and we will have to keep our eyes for a better solution at some point for remote interviews.

**Comment by jessegreenberg** [comment]
That sounds great to me @terracoda, thanks. Closing this issue since we are not going to work on recording a11y events from the DOM or use sim state to  record playback for now. Working on a11y+phet-io features will be more thoroughly investigated in https://github.com/phetsims/phet-io/issues/1205 when  we decide to allocate time for that.

**Comment by samreid** [comment]
> I think it is safe to close, and we will have to keep our eyes out for a better solution at some point for remote interviews.

Metacog may be able to capture states or input events for later playback (without microphone audio), let me or @zepumph know if we should try it.

**Comment by zepumph** [comment]
Yes, but right now keyboard focus highlight state isn't transferred in mirror-inputs, so I think we would need to do some work first.

**Comment by samreid** [comment]
Good point, thanks!

**Comment by zepumph** [comment]
Here is the central issue that would need to be solved first, then I would say that this great idea would be worth pursuing!

https://github.com/phetsims/phet-io/issues/1205
