### ISSUE TITLE
JT/OL versions for Sound + Description

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#83]
need to know what versions of JT and OL we want to be updated with the latest description. Once that's done, @jbphet can create these, and then we'll need to do some testing/checking. 

So, once you what version you'd like to roll with for initial interviews, let JB know.

**Comment by briannatomlinson** [comment]
Do you want me to do work with JT while we're waiting on the rest of the description for RIAW to be completed? Or, would you rather I just do some of the more free form work with the GLASS employees for this?

**Comment by emily-phet** [comment]
@briannatomlinson I think using JT and OL (both have descriptions and sound) would be great. They're different in interesting ways.

**Comment by briannatomlinson** [comment]
I'm not sure if there's a particular version of OL that you feel is most appropriate, based on our discussion from [https://docs.google.com/spreadsheets/d/1QbjVep_uMSn-KD8dChtFQRkLKOrYH28IqS-bhYrTEoc/edit?usp=sharing](url) 

Based on the OL surveys alone, I'd say the best ones for comprehension were for the pitch mapping or tempo/pitch mapping only for current.

I'm not sure if you or John have more input on the JT version? I know @jbphet has been working a lot on that mix version but I don't know how much of that needs to be incorporated/changed in a plain version of JT. If there's a list of optimal settings that would be easy to transfer I can do so.

**Comment by briannatomlinson** [comment]
My guess is that it's the [John Travoltage - enhanced sound design snapshot 1/29/2018 ](https://www.colorado.edu/physics/phet/dev/html/phet-io-wrapper-sonification/1.0.0-dev.52/phet-io-wrapper-sonification/john-travoltage/html/john-travoltage-sonification.html?sonificationFile=sonificationMix&accessibility) ?

**Comment by jbphet** [comment]
I've updated the phet-io version used in all wrappers, and this is published in version v1.0.0-dev.53, see https://www.colorado.edu/physics/phet/dev/html/phet-io-wrapper-sonification/1.0.0-dev.53/phet-io-wrapper-sonification/sonification.html.  However, some of the OL versions are broken due to unrelated issues, and @briannatomlinson is investigating this.

As for JT, the descriptions haven't been updated recently, so the versions currently wrapped are essentially up to date.

**Comment by briannatomlinson** [comment]
Most of these issues are fixed in now, see https://github.com/phetsims/phet-io-wrapper-sonification/issues/42.

I'll be working to do a few updates before this can get closed out:
OL: one of the looping current sounds + some other options if we have time
Without the sliders (either 2 or 3 from the options2)

@jbphet  does the JT - enhanced sound design snapshot 1/29/2018 include the updates for the interviews that Emily mentioned doing? I think it's the most up-to-date sounds & I plan to use it unless you think there will be any major changes

**Comment by jbphet** [comment]
@briannatomlinson - the snapshot has everything except the updated foot dragging sound.  Also, the dev.54 version of this snapshot has an updated version of the ambient sound for electrons in the body which I and Ashton both like *less* than the previous version.  If you're gearing up for some interviews, I'd like to republish this with the foot dragging added and the previous ambient electron sound.  Agreed? @emily-phet - does that sound like a good plan to you?

**Comment by briannatomlinson** [comment]
If @emily-phet  is good with that version, I'm good. I haven't looked at JT as much recently, so whatever version you guys want to move forward with is fine with me.

**Comment by briannatomlinson** [comment]
@jbphet JT has been updated from the version you & Ashton didn't like, right?

**Comment by jbphet** [comment]
Yes, the foot dragging sound has been updated and reviewed.  Should be good to go.
